apiVersion: v1
kind: ConfigMap
metadata:
  name: svc2-config
  namespace: go-k8s
data:
  SVC1_ENDPOINT: "http://svc1-name"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2
  namespace: go-k8s
  labels:
    app: svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
      - image: ttl.sh/iamsumit/svc2:go-k8s
        name: svc2
        imagePullPolicy: Always
        env:
        - name: SVC1_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: svc2-config
              key: SVC1_ENDPOINT
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '250m'
              memory: '256Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: svc2
  namespace: go-k8s
  labels:
    app: svc2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: svc2
  type: ClusterIP

---
# metrics-server can be used to collect the resource usage metric.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: svc2-name
  namespace: go-k8s
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc2
  targetCPUUtilizationPercentage: 10
